### ISSUE TITLE
Missing links in AIDO client protocol.md

### ISSUE THREAD

**Issue by heathcliffYang** [idsc-frazzoli/amod#176]
Hi,

I want to use docker and search some documentation or tutorials about this.

I found many links in `AIDO client protocol.md` are missing.

Could you fix up the lack of documentation?

Thank you!

**Comment by JoelGaechter** [comment]
The version on github is now up-to-date.
Since we are not part of the current [AI Driving Olympics (AI-DO)](https://www.duckietown.org/research/AI-Driving-olympics) many of the links were no longer valid.
